import threading 
import os
import sys
import trace
def runapp(str):
	print("running for thread number",str)
	os.system("sh ubuntu_multithreading_script.sh")
	

if __name__ == "__main__": 
    # creating thread 
    t1 = threading.Thread(target=runapp, args=(1,)) 
    #t2 = threading.Thread(target=runapp, args=(2,))
    #t3 = threading.Thread(target=runapp, args=(3,)) 
    #t4 = threading.Thread(target=runapp, args=(4,)) 
    #t5 = threading.Thread(target=runapp, args=(5,))
    #t6 = threading.Thread(target=runapp, args=(6,))
    #t7 = threading.Thread(target=runapp, args=(7,)) 
    #t8 = threading.Thread(target=runapp, args=(8,)) 
    #t9 = threading.Thread(target=runapp, args=(9,)) 
    #t10 = threading.Thread(target=runapp, args=(10,))
    #t11 = threading.Thread(target=runapp, args=(11,)) 
    #t12 = threading.Thread(target=runapp, args=(12,)) 
    #t13 = threading.Thread(target=runapp, args=(13,))
    #t14 = threading.Thread(target=runapp, args=(14,))
    #t15 = threading.Thread(target=runapp, args=(15,)) 
    #t16 = threading.Thread(target=runapp, args=(16,)) 
    #t17 = threading.Thread(target=runapp, args=(17,)) 
    #t18 = threading.Thread(target=runapp, args=(18,))
    #t19 = threading.Thread(target=runapp, args=(19,)) 
    #t20 = threading.Thread(target=runapp, args=(20,)) 
    #t21 = threading.Thread(target=runapp, args=(21,))
    #t22 = threading.Thread(target=runapp, args=(22,))
    #t23 = threading.Thread(target=runapp, args=(23,)) 
    #t24 = threading.Thread(target=runapp, args=(24,)) 
    #t25 = threading.Thread(target=runapp, args=(25,)) 
    #t26 = threading.Thread(target=runapp, args=(26,))
    #t27 = threading.Thread(target=runapp, args=(27,)) 
    #t28 = threading.Thread(target=runapp, args=(28,)) 
    #t29 = threading.Thread(target=runapp, args=(29,))
    #t30 = threading.Thread(target=runapp, args=(30,))
    #t31 = threading.Thread(target=runapp, args=(31,)) 
    #t32 = threading.Thread(target=runapp, args=(32,)) 
     
     
    # starting thread 1 
    t1.start() 
    #t2.start()
    #t3.start() 
    #t4.start() 
    #t5.start() 
    #t6.start()
    #t7.start() 
    #t8.start() 
    #t9.start()
    #t10.start() 
    #t11.start() 
    #t12.start() 
    #t13.start()
    #t14.start() 
    #t15.start() 
    #t16.start()
    #t17.start() 
    #t18.start()
    #t19.start() 
    #t20.start() 
    #t21.start() 
    #t22.start()
    #t23.start() 
    #t24.start() 
    #t25.start()
    #t26.start() 
    #t27.start() 
    #t28.start() 
    #t29.start()
    #t30.start() 
    #t31.start() 
    #t32.start()
  
    # wait until thread 1 is completely executed 
    t1.join() 
    #t2.join() 
    #t3.join() 
    #t4.join() 
    #t5.join() 
    #t6.join() 
    #t7.join() 
    #t8.join() 
    #t9.join() 
    #t10.join() 
    #t11.join() 
    #t12.join() 
    #t13.join() 
    #t14.join() 
    #t15.join()
    #t16.join() 
    #t17.join() 
    #t18.join() 
    #t19.join() 
    #t20.join() 
    #t21.join() 
    #t22.join() 
    #t23.join() 
    #t24.join() 
    #t25.join() 
    #t26.join() 
    #t27.join() 
    #t28.join() 
    #t29.join() 
    #t30.join() 
    #t31.join()
    #t32.join() 


    #t1.kill()
    #t2.kill()
    #t3.kill()
    #t4.kill()
    #t5.kill()
    # both threads completely executed 
    print("Done!") 




